package org.yoqu.cms.model;

import org.yoqu.cms.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment();
}
