package org.yoqu.cms.model;

import org.yoqu.cms.model.base.BaseNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Node extends BaseNode<Node> {
	public static final Node dao = new Node();
}
