package org.yoqu.cms.model;
import org.yoqu.cms.model.base.BaseUser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();


	public List<User> finduserByNamePasswordOrName(String... parameters){
		if (parameters.length==2){
			return find("select * from user where name=? and password=?",parameters);
		}
		else if(parameters.length==1){
			return find("select * from user where name=?",parameters);
		}
		else return null;
	}

	@Override
	public String toString() {
		return "ID:"+getId()+"Name: "+getName()+" Password: "+getPassword()+" createDate: "+getCreateDate()+" lastDate:"+getLastDate()+"role: "+getRole();
	}
}
