package org.yoqu.cms.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleAccess<M extends BaseRoleAccess<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRId(java.lang.Integer rId) {
		set("rId", rId);
	}

	public java.lang.Integer getRId() {
		return get("rId");
	}

	public void setAccess(java.lang.String access) {
		set("access", access);
	}

	public java.lang.String getAccess() {
		return get("access");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
