package org.yoqu.blog.model;

import org.yoqu.blog.model.base.BaseModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module();
}
