package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Client extends BaseClient<Client> {
	public static final Client dao = new Client();
}
