package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseDictionary;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
    public static final Dictionary dao = new Dictionary();

    public List<Dictionary> getDictionaryList() {
        return find("select * from dictionary");
    }

    public List<Dictionary> getDictionaryList(Integer dictionType) {
        return find("select * from dictionary where typeid=?", dictionType);
    }
}
