package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseDictionaryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictionaryType extends BaseDictionaryType<DictionaryType> {
	public static final DictionaryType dao = new DictionaryType();
}
