package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseFile;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File();

	public void updateFile(String files,String moduleName,int fid){
		List<File> newFiles =dao.find("select * from file where id in(?) and fid=-1", files);
		if (newFiles.size() > 0) {
			for (File f:newFiles){
				f.setFid(fid);
				f.setModule(moduleName);
				f.update();
			}
		}
	}
    public List<File> findDeleteFile(String files,int fid){
        return  File.dao.find("select * from file where id not in(?) and fid=?", files, fid);
    }
}
