package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File();
}
