package org.yoqu.cms.core.model;

import com.jfinal.plugin.activerecord.Config;
import com.jfinal.plugin.activerecord.DbKit;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.yoqu.cms.core.model.base.BaseMenu;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
    public static final Menu dao = new Menu();

    private List<Menu> menuList;

    public List<Menu> getMenuList() {
        return menuList;
    }
    public void setMenuList(List<Menu> menuList){
        this.menuList=menuList;
    }
    public void setMenuListToAttr(){
        getAttrs().put("menuList",menuList);
    }
    public void addChild(Menu menu) {
        if (menuList == null) {
            menuList = new ArrayList<>();
        }
        menuList.add(menu);
    }

    public MenuType getMenuType() {
        return MenuType.dao.findById(getType());
    }


}
