package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseMenuType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuType extends BaseMenuType<MenuType> {
	public static final MenuType dao = new MenuType();
}
