package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseMenuType;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuType extends BaseMenuType<MenuType> {
	public static final MenuType dao = new MenuType();

	public List<MenuType> findAllMenuType(){
		return find("select * from menu_type where is_delete=0");
	}

	public MenuType findByIdFirst(int id){
		return findFirst("select * from menu_type where is_delete=0 and id=?",id);
	}
}
