package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();

	public MenuType getMenuType(){
		return MenuType.dao.findById(getType());
	}
}
