package org.yoqu.cms.core.model;

import org.yoqu.cms.core.admin.modules.user.UserInvoke;
import org.yoqu.cms.core.model.base.BaseNode;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Node extends BaseNode<Node> {
    public static final Node dao = new Node();

    public User getUser() {
        return UserInvoke.getInstance().findUserById(getUid());
    }

    public List<File> getListFile() {
        return File.dao.find("select * from file where fid=? and module='node'", getId());
    }
}
