package org.yoqu.cms.core.model;

import org.yoqu.cms.core.Constant.Constant;
import org.yoqu.cms.core.model.base.BaseRole;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
    public static final Role dao = new Role();

    public  Role findAdminRole() {
        List<Role> roles = dao.find("select * from role where name=?", Constant.ROLE_ADMIN);
        if (roles.size() > 0) {
            return roles.get(0);
        } else
            return null;
    }
}
