package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseRoleAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAccess extends BaseRoleAccess<RoleAccess> {
	public static final RoleAccess dao = new RoleAccess();
}
