package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Url extends BaseUrl<Url> {
	public static final Url dao = new Url();
}
