package org.yoqu.cms.core.model;

import org.yoqu.cms.core.model.base.BaseUser;

/**
 * Generated by JFinal.
 */

public class User extends BaseUser<User> {
    public static final User dao = new User();


    public Role getRole() {
        return Role.dao.findById(getRid());
    }


    @Override
    public String toString() {
        return "ID:" + getId() + "Name: " + getName() + " Password: " + getPassword() + " createDate: " + getCreateDate() + " lastDate:" + getLastDate() + "role: " + getRole();
    }

}
