package org.yoqu.cms.core.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import org.yoqu.cms.core.admin.Constant.SystemVariable;
import org.yoqu.cms.core.config.Constant;
import org.yoqu.cms.core.model.base.BaseUser;
import org.yoqu.cms.core.util.FinalProxy;

import java.util.List;

/**
 * Generated by JFinal.
 */

public class User extends BaseUser<User> {
    public static final User dao = new User();
    public List<User> finduserByNamePasswordOrName(String... parameters) {
        if (parameters.length == 2) {
            return find("select * from user where name=? and password=? and is_delete=0", parameters);
        } else if (parameters.length == 1) {
            return find("select * from user where name=? and is_delete=0", parameters);
        } else if (parameters.length == 0) {
            return find("select * from user where is_delete=0");
        } else return null;
    }

    public Role getRole() {
        return Role.dao.findById(getRid());
    }

    public Page<User> findUserByPage(int pageNumber) {
        return paginate(pageNumber, Integer.parseInt(SystemVariable.get(Constant.PAGE_SIZE).trim()), "select *", "from user where is_delete=0 order by createDate desc");
    }

    public boolean softDelete(int uid) {
        if (Db.update("update user set is_delete=1 where id=?", uid) > 0) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public String toString() {
        return "ID:" + getId() + "Name: " + getName() + " Password: " + getPassword() + " createDate: " + getCreateDate() + " lastDate:" + getLastDate() + "role: " + getRole();
    }

}
