package org.yoqu.cms.core.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import org.yoqu.cms.core.admin.Constant.SystemVariable;
import org.yoqu.cms.core.config.Constant;
import org.yoqu.cms.core.model.base.BaseUser;
import org.yoqu.cms.core.util.FinalProxy;

import java.util.List;

/**
 * Generated by JFinal.
 */

public class User extends BaseUser<User> {
    public static final User dao = new User();


    public Role getRole() {
        return Role.dao.findById(getRid());
    }


    @Override
    public String toString() {
        return "ID:" + getId() + "Name: " + getName() + " Password: " + getPassword() + " createDate: " + getCreateDate() + " lastDate:" + getLastDate() + "role: " + getRole();
    }

}
